<?php
/*
 * Copyright (c) 2012-2016, Hofmänner New Media.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This file is part of the N2N FRAMEWORK.
 *
 * The N2N FRAMEWORK is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software Foundation, either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * N2N is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details: http://www.gnu.org/licenses/
 *
 * The following people participated in this project:
 *
 * Andreas von Burg.....: Architect, Lead Developer
 * Bert Hofmänner.......: Idea, Community Leader, Marketing
 * Thomas Günther.......: Developer, Hangar
 */
namespace n2n\persistence\orm\store\action\supply;

use n2n\persistence\orm\store\action\PersistAction;
use n2n\util\ex\IllegalStateException;
use n2n\persistence\orm\store\PersistenceOperationException;
use n2n\persistence\orm\property\CascadableEntityProperty;

class PersistSupplyJob extends SupplyJobAdapter {
	private $valueHashes = array();
	private $prepared = false;

	public function __construct(PersistAction $persistAction, array $oldValueHashes = null) {
		parent::__construct($persistAction, $oldValueHashes);
	}

	public function getPersistAction() {
		return $this->entityAction;
	}
	
	public function isInsert() {
		return $this->entityAction->isNew();
	}
	
	public function isUpdate() {
		return !$this->entityAction->isNew();
	}
	
	public function isRemove() {
		return false;
	}

	public function setValueHashes(array $valueHashes) {
		$this->valueHashes = $valueHashes;
	}

	public function getValueHashes() {
		return $this->valueHashes;
	}
	
	private function getValueHash($propertyName) {
		IllegalStateException::assertTrue(array_key_exists($propertyName, $this->valueHashes));
		return $this->valueHashes[$propertyName];
	}

	public function prepare() {
		parent::prepare();
		
		if ($this->isDisabled()) return;

		$new = $this->isInsert();
		
		foreach ($this->entityAction->getEntityModel()->getEntityProperties()
				as $propertyName => $entityProperty) {
			if (!($entityProperty instanceof CascadableEntityProperty)) continue;

			$oldValueHash = null;
			if (!$new) {
				$oldValueHash = $this->getOldValueHash($propertyName);
				if ($oldValueHash === $this->getValueHash($propertyName)) continue;
			}
			
			$entityProperty->prepareSupplyJob($this->values[$propertyName], $oldValueHash, $this);
		}
	}

	private function validateId() {
		if (null !== $this->entityAction->getId()) return;

		$idDef = $this->entityAction->getEntityModel()->getIdDef();
		if (!$idDef->isGenerated()) {
			throw new PersistenceOperationException('Id property '
					. $idDef->getEntityProperty()->toPropertyString()
					. ' must contain a non-null value because it will not be generated by the database.');
		}
	}

	public function execute() {
		if ($this->isDisabled()) return;

		IllegalStateException::assertTrue($this->init);
		
		$this->validateId();

		$entityModel = $this->entityAction->getEntityModel();
		$idDef = $entityModel->getIdDef();
		$idPropertyName = $idDef->getPropertyName();
		foreach ($entityModel->getEntityProperties() as $propertyName => $property) {
			if ($idPropertyName === $propertyName && ($idDef->isGenerated()
					|| !$this->entityAction->isNew())) {
				continue;
			}
				
			$oldValueHash = null;
			if (!$this->entityAction->isNew()) {
				$oldValueHash = $this->getOldValueHash($propertyName);
				if ($oldValueHash === $this->getValueHash($propertyName)) continue;
			}
			
			$property->supplyPersistAction($this->getValue($propertyName), $oldValueHash, 
					$this->entityAction);
		}

		foreach ($entityModel->getActionDependencies() as $actionDependency) {
			$actionDependency->persistActionSupplied($this->entityAction);
		}
		
		$that = $this;
		$this->entityAction->executeAtEnd(function () use ($that) {
			$em = $that->getActionQueue()->getEntityManager();
			$this->entityAction->getActionQueue()->getEntityManager()->getPersistenceContext()
					->updateValueHashes($that->entityAction->getEntityObj(),
							$that->values, $that->valueHashes, $em);
		});
	}
}
