<?php
/*
 * Copyright (c) 2012-2016, Hofmänner New Media.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This file is part of the N2N FRAMEWORK.
 *
 * The N2N FRAMEWORK is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software Foundation, either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * N2N is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details: http://www.gnu.org/licenses/
 *
 * The following people participated in this project:
 *
 * Andreas von Burg.....: Architect, Lead Developer
 * Bert Hofmänner.......: Idea, Frontend UI, Community Leader, Marketing
 * Thomas Günther.......: Developer, Hangar
 */
namespace n2n\persistence\orm\store\action\supply;

use n2n\persistence\orm\store\action\PersistAction;
use n2n\util\ex\IllegalStateException;
use n2n\persistence\orm\store\PersistenceOperationException;
use n2n\persistence\orm\store\ValueHashCol;
use n2n\persistence\orm\store\ValueHash;
use n2n\persistence\orm\store\ValueHashColFactory;
use n2n\persistence\orm\store\action\meta\ActionMeta;

class PersistSupplyJob extends SupplyJobAdapter {
	private ?ValueHashCol $valueHashCol = null;
	private bool $prepared = false;

	public function __construct(private PersistAction $persistAction, ?ValueHashCol $oldValueHashCol = null) {
		parent::__construct($persistAction, $oldValueHashCol);
	}

	public function getPersistAction() {
		return $this->entityAction;
	}

	function getActionMeta(): ?ActionMeta {
		return $this->persistAction->getMeta();
	}

	public function isInsert() {
		return $this->entityAction->isNew();
	}
	
	public function isUpdate() {
		return !$this->entityAction->isNew();
	}
	
	public function isRemove() {
		return false;
	}

	/**
	 * @param ValueHashCol|null $valueHashCol
	 */
	public function setValueHashCol(?ValueHashCol $valueHashCol): void {
		$this->valueHashCol = $valueHashCol;
	}

	/**
	 * @return \n2n\persistence\orm\store\ValueHashCol|null
	 */
	public function getValueHashCol() {
		return $this->valueHashCol;
	}
	
	/**
	 * @param string $propertyString
	 * @return ValueHash
	 */
	private function getValueHash($propertyString) {
		IllegalStateException::assertTrue($this->valueHashCol !== null);
		return $this->valueHashCol->getValueHash($propertyString);
	}

	public function prepare(): void {
// 		parent::prepare();
		
		if ($this->isDisabled()) return;

		$new = $this->isInsert();

		$entityModel = $this->entityAction->getEntityModel();
		$idDef = $entityModel->getIdDef();
		$idPropertyString = $idDef->getEntityProperty()->toPropertyString();

//		$this->persistAction->getMeta()->unmarkAllChanges();
		foreach ($this->entityAction->getEntityModel()->getEntityProperties() as $entityProperty) {
			$propertyString = $entityProperty->toPropertyString();
			if ($idPropertyString === $propertyString && ($idDef->isGenerated() || !$this->entityAction->isNew())) {
				continue;
			}

			$valueHash = $this->getValueHash($propertyString);
			$oldValueHash = null;
			if (!$new) {
				$oldValueHash = $this->getOldValueHash($propertyString);
				if ($oldValueHash->matches($valueHash)) {
					$this->persistAction->getMeta()->unmarkChange($entityProperty);
					continue;
				}
			}
		
			$entityProperty->prepareSupplyJob($this, $this->values[$propertyString], $valueHash, $oldValueHash);
			$this->persistAction->getMeta()->markChange($entityProperty);
		}
	}

	private function validateId(): void {
		if (null !== $this->entityAction->getId()) return;

		$idDef = $this->entityAction->getEntityModel()->getIdDef();
		if (!$idDef->isGenerated()) {
			throw new PersistenceOperationException('Id property '
					. $idDef->getEntityProperty()->toPropertyString()
					. ' must contain a non-null value because it will not be generated by the database.');
		}
	}

	public function execute() {
		if ($this->isDisabled()) return;

		IllegalStateException::assertTrue($this->init);
		
		$this->validateId();

		$entityModel = $this->entityAction->getEntityModel();
		$idDef = $entityModel->getIdDef();
		$idPropertyString = $idDef->getEntityProperty()->toPropertyString();
		foreach ($entityModel->getEntityProperties() as $property) {
			$propertyString = $property->toPropertyString();
			if ($idPropertyString === $propertyString && ($idDef->isGenerated() || !$this->persistAction->isNew())) {
				continue;
			}

			$oldValueHash = null;
			$valueHash = $this->getValueHash($propertyString);
			if (!$this->persistAction->isNew()) {
				$oldValueHash = $this->getOldValueHash($propertyString);
				if ($oldValueHash->matches($valueHash)) continue;
			}

			$property->supplyPersistAction($this->persistAction, $this->getValue($propertyString), $valueHash, $oldValueHash);
		}

//		foreach ($entityModel->getActionDependencies() as $actionDependency) {
//			$actionDependency->persistActionSupplied($this->entityAction);
//		}
		
		$that = $this;
		$this->entityAction->executeAtEnd(function () use ($that) {
			$em = $that->getActionQueue()->getEntityManager();
			$entityModel = $this->entityAction->getEntityModel();
			
			if ($this->entityAction->isNew() && $entityModel->getIdDef()->isGenerated()) {
				$idEntityProperty = $this->entityAction->getEntityModel()->getIdDef()->getEntityProperty();
				ValueHashColFactory::updateId($idEntityProperty, $this->entityAction->getId(), $that->valueHashCol, $em);
			}
			
			$em->getPersistenceContext()
					->updateValueHashes($that->entityAction->getEntityObj(), $that->valueHashCol);
			
		});
	}
}
